VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CCtpt"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public ID As Long
Public Nome As String
Public RazaoSocial As String
Public CNPJ As String
Public Administrador As String
Public CNPJADM As String
Public Procuradores As String
Public CNPJProc As String
Public Endereco As String
Public Telefone As String
Public email As String
Public Atividade As String
Public PerfilRisco As String
Public Atualizado As Date

