using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Capitania.EntityFrameworkCore
{
    public static class DBParametersConstants
    {
        public const string HistFileName = "001";
        public const string HistFileTab = "002";
        public const string HistFileIFIX = "003";
        public const string HistFileIPCA2Y = "004";
        public const string HistFileIPCA5Y = "005";
        public const string HistFileIPCA10Y = "006";
        public const string HistFilePath = "007";
        public const string HistFileIMAB5 = "008";
        public const string HistFilePRE2Y = "009";
        public const string HistFilePRE5Y = "010";
        public const string HistFileDolar = "011";
        public const string HistFileIDA = "012";
        public const string HistFileRatingsTab = "013";
        public const string HistFileQuotaTab = "014";
        public const string PosicFilePrefix = "015";
        public const string RedemptionFilePath = "016";
        public const string RedemptionFileName = "017";
        public const string RedemptionFileTab = "018";
        public const string ConcentrationFundID = "019";
        public const string ConcentrationProperty1 = "020";
        public const string ConcentrationProperty2 = "021";
        public const string ConcentrationProperty3 = "022";
        public const string RedemptionFileTransferTab = "023";
        public const string ShareFilePath = "024";
        public const string ShareFileName = "025";
        public const string EWMA = "026";
        public const string EDFAAA = "027";
        public const string EDFAA = "028";
        public const string EDFA = "029";
        public const string EDFBBB = "030";
        public const string EDFBB = "031";
        public const string EDFB = "032";
        public const string EDFCCC = "033";
        public const string EDFAAA_ASK = "034";
        public const string EDFAA_ASK = "035";
        public const string EDFA_ASK = "036";
        public const string EDFBBB_ASK = "037";
        public const string EDFBB_ASK = "038";
        public const string EDFB_ASK = "039";
        public const string EDFCCC_ASK = "040";
        public const string CreditRatingProperty = "041";
        public const string IRBProperty = "042";
        public const string LastRatingProperty = "043";
        public const string LVV = "044";
        public const string LVQ = "045";
        public const string LVP = "046";
        public const string LSV = "047";
        public const string LSQ = "048";
        public const string LSP = "049";
        public const string LEV = "050";
        public const string LEQ = "051";
        public const string LEP = "052";
        public const string LUV = "053";
        public const string LUQ = "054";
        public const string LUP = "055";
        public const string WarnAt20 = "056";
        public const string NegsFilePrefix = "057";
        public const string CRMDatabase = "058";
        public const string RFETradeSheet = "059";
        public const string RFETradeTab = "060";
        public const string PricingFilePrefix = "061";
        public const string GenLvlDI = "062";
        public const string GenLvlInflation = "063";
        public const string CredLGD = "064";
        public const string CredLGDSec = "065";
        public const string CredCorrel = "066";
        public const string CredCorrelIntra = "067";
        public const string CredGroupProperty = "068";
        public const string FIIFileName = "069";
        public const string FIIFileTab = "070";
        public const string XMLANBIMAPath = "071";
        public const string XMLANBIMAPrefix = "072";
        public const string ISINDATABASE = "073";
        public const string FIIADTVTab = "074";
        public const string BlotterFileName = "075";
        public const string RStress1 = "076";
        public const string RStress2 = "077";
        public const string RStress3 = "078";
        public const string RStress4 = "079";
        public const string RStress5 = "080";
        public const string email = "081";
        public const string senha = "082";

    }
}
